"""Pydantic v2 schemas for the public API."""

from covet.schemas.audit import AuditLogRead
from covet.schemas.auth import (
    LoginRequest,
    MeUpdate,
    OIDCProviderInfo,
    RegisterRequest,
    SessionInfo,
    TokenInfo,
)
from covet.schemas.category import CategoryRead
from covet.schemas.collection import (
    CollectionCreate,
    CollectionRead,
    CollectionUpdate,
    MembershipCreate,
    MembershipDetail,
    MembershipRead,
    MembershipUpdate,
    ShareLinkCreate,
    ShareLinkRead,
)
from covet.schemas.contact import ContactCreate, ContactRead, ContactUpdate
from covet.schemas.document import DocumentRead, DocumentUpdate
from covet.schemas.inventory import (
    DueAlertRead,
    ItemLotCreate,
    ItemLotRead,
    ItemLotUpdate,
    RestockRequest,
)
from covet.schemas.invitation import (
    InvitationCreate,
    InvitationCreated,
    InvitationPreview,
    InvitationRead,
)
from covet.schemas.item import (
    ItemArchiveUpdate,
    ItemBulkArchiveRequest,
    ItemBulkDeleteRequest,
    ItemBulkDeleteResponse,
    ItemBulkLendRequest,
    ItemBulkPatchRequest,
    ItemBulkRestoreRequest,
    ItemBulkTagRequest,
    ItemCreate,
    ItemFlagUpdate,
    ItemRead,
    ItemUpdate,
)
from covet.schemas.item_template import (
    ItemTemplateCreate,
    ItemTemplateRead,
    ItemTemplateUpdate,
    TemplateField,
)
from covet.schemas.loan import LoanCreate, LoanRead, LoanUpdate
from covet.schemas.location import LocationCreate, LocationKind, LocationRead, LocationUpdate
from covet.schemas.maintenance import (
    MaintenanceTaskCreate,
    MaintenanceTaskRead,
    MaintenanceTaskUpdate,
)
from covet.schemas.manual_bundle import (
    BundleAssetRead,
    BundleAssetUpdate,
    ManualBundleCreate,
    ManualBundleRead,
    ManualBundleUpdate,
)
from covet.schemas.photo import PhotoFromUrl, PhotoRead, PhotoUpdate
from covet.schemas.sync import (
    SyncChange,
    SyncChangeUpload,
    SyncDocSummary,
    SyncPullResponse,
    SyncPushRequest,
    SyncPushResponse,
    SyncSnapshotResponse,
    SyncSnapshotUpload,
)
from covet.schemas.tag import TagCreate, TagRead, TagUpdate
from covet.schemas.user import UserCreate, UserRead, UserUpdate
from covet.schemas.webhook import (
    WebhookCreate,
    WebhookDeliveryRead,
    WebhookRead,
    WebhookUpdate,
)

__all__ = [
    "AuditLogRead",
    "BundleAssetRead",
    "BundleAssetUpdate",
    "CategoryRead",
    "CollectionCreate",
    "CollectionRead",
    "CollectionUpdate",
    "ContactCreate",
    "ContactRead",
    "ContactUpdate",
    "DocumentRead",
    "DocumentUpdate",
    "DueAlertRead",
    "InvitationCreate",
    "InvitationCreated",
    "InvitationPreview",
    "InvitationRead",
    "ItemArchiveUpdate",
    "ItemBulkArchiveRequest",
    "ItemBulkDeleteRequest",
    "ItemBulkDeleteResponse",
    "ItemBulkLendRequest",
    "ItemBulkPatchRequest",
    "ItemBulkRestoreRequest",
    "ItemBulkTagRequest",
    "ItemCreate",
    "ItemFlagUpdate",
    "ItemLotCreate",
    "ItemLotRead",
    "ItemLotUpdate",
    "ItemRead",
    "ItemTemplateCreate",
    "ItemTemplateRead",
    "ItemTemplateUpdate",
    "ItemUpdate",
    "LoanCreate",
    "LoanRead",
    "LoanUpdate",
    "LocationCreate",
    "LocationKind",
    "LocationRead",
    "LocationUpdate",
    "LoginRequest",
    "MaintenanceTaskCreate",
    "MaintenanceTaskRead",
    "MaintenanceTaskUpdate",
    "ManualBundleCreate",
    "ManualBundleRead",
    "ManualBundleUpdate",
    "MeUpdate",
    "MembershipCreate",
    "MembershipDetail",
    "MembershipRead",
    "MembershipUpdate",
    "OIDCProviderInfo",
    "PhotoFromUrl",
    "PhotoRead",
    "PhotoUpdate",
    "RegisterRequest",
    "RestockRequest",
    "SessionInfo",
    "ShareLinkCreate",
    "ShareLinkRead",
    "SyncChange",
    "SyncChangeUpload",
    "SyncDocSummary",
    "SyncPullResponse",
    "SyncPushRequest",
    "SyncPushResponse",
    "SyncSnapshotResponse",
    "SyncSnapshotUpload",
    "TagCreate",
    "TagRead",
    "TagUpdate",
    "TemplateField",
    "TokenInfo",
    "UserCreate",
    "UserRead",
    "UserUpdate",
    "WebhookCreate",
    "WebhookDeliveryRead",
    "WebhookRead",
    "WebhookUpdate",
]
