"""Pydantic v2 schemas for the public API."""

from tangible.schemas.audit import AuditLogRead
from tangible.schemas.auth import (
    LoginRequest,
    MeUpdate,
    OIDCProviderInfo,
    RegisterRequest,
    SessionInfo,
    TokenInfo,
)
from tangible.schemas.category import CategoryRead
from tangible.schemas.collection import (
    CollectionCreate,
    CollectionRead,
    CollectionUpdate,
    MembershipCreate,
    MembershipDetail,
    MembershipRead,
    MembershipUpdate,
    ShareLinkCreate,
    ShareLinkRead,
)
from tangible.schemas.contact import ContactCreate, ContactRead, ContactUpdate
from tangible.schemas.document import DocumentRead, DocumentUpdate
from tangible.schemas.grocery import (
    GroceryAisleCreate,
    GroceryAisleRead,
    GroceryAisleUpdate,
    GroceryCount,
    GroceryFeedEntry,
    GroceryItemCreate,
    GroceryItemRead,
    GroceryItemUpdate,
    GroceryPurchaseRequest,
    GrocerySource,
    GroceryStoreCreate,
    GroceryStoreRead,
    GroceryStoreUpdate,
)
from tangible.schemas.inventory import (
    DueAlertRead,
    ItemLotCreate,
    ItemLotRead,
    ItemLotUpdate,
    RestockRequest,
)
from tangible.schemas.invitation import (
    InvitationCreate,
    InvitationCreated,
    InvitationPreview,
    InvitationRead,
)
from tangible.schemas.item import (
    ItemArchiveUpdate,
    ItemBulkArchiveRequest,
    ItemBulkDeleteRequest,
    ItemBulkDeleteResponse,
    ItemBulkLendRequest,
    ItemBulkPatchRequest,
    ItemBulkRestoreRequest,
    ItemBulkTagRequest,
    ItemCreate,
    ItemFlagUpdate,
    ItemRead,
    ItemUpdate,
)
from tangible.schemas.item_template import (
    ItemTemplateCreate,
    ItemTemplateRead,
    ItemTemplateUpdate,
    TemplateField,
)
from tangible.schemas.loan import LoanCreate, LoanRead, LoanUpdate
from tangible.schemas.location import LocationCreate, LocationKind, LocationRead, LocationUpdate
from tangible.schemas.maintenance import (
    ChoreCompletePayload,
    ChoreCompletionRead,
    ChoreCreate,
    ChoreRead,
    ChoreUpdate,
    MaintenanceCompletePayload,
    MaintenanceCompletionRead,
    MaintenanceTaskCreate,
    MaintenanceTaskRead,
    MaintenanceTaskUpdate,
)
from tangible.schemas.manual_bundle import (
    BundleAssetRead,
    BundleAssetUpdate,
    ManualBundleCreate,
    ManualBundleRead,
    ManualBundleUpdate,
)
from tangible.schemas.photo import PhotoFromUrl, PhotoRead, PhotoUpdate
from tangible.schemas.sync import (
    SyncChange,
    SyncChangeUpload,
    SyncDocSummary,
    SyncPullResponse,
    SyncPushRequest,
    SyncPushResponse,
    SyncSnapshotResponse,
    SyncSnapshotUpload,
)
from tangible.schemas.tag import TagCreate, TagRead, TagUpdate
from tangible.schemas.user import UserCreate, UserRead, UserUpdate
from tangible.schemas.webhook import (
    WebhookCreate,
    WebhookDeliveryRead,
    WebhookRead,
    WebhookUpdate,
)

__all__ = [
    "AuditLogRead",
    "BundleAssetRead",
    "BundleAssetUpdate",
    "CategoryRead",
    "ChoreCompletePayload",
    "ChoreCompletionRead",
    "ChoreCreate",
    "ChoreRead",
    "ChoreUpdate",
    "CollectionCreate",
    "CollectionRead",
    "CollectionUpdate",
    "ContactCreate",
    "ContactRead",
    "ContactUpdate",
    "DocumentRead",
    "DocumentUpdate",
    "DueAlertRead",
    "GroceryAisleCreate",
    "GroceryAisleRead",
    "GroceryAisleUpdate",
    "GroceryCount",
    "GroceryFeedEntry",
    "GroceryItemCreate",
    "GroceryItemRead",
    "GroceryItemUpdate",
    "GroceryPurchaseRequest",
    "GrocerySource",
    "GroceryStoreCreate",
    "GroceryStoreRead",
    "GroceryStoreUpdate",
    "InvitationCreate",
    "InvitationCreated",
    "InvitationPreview",
    "InvitationRead",
    "ItemArchiveUpdate",
    "ItemBulkArchiveRequest",
    "ItemBulkDeleteRequest",
    "ItemBulkDeleteResponse",
    "ItemBulkLendRequest",
    "ItemBulkPatchRequest",
    "ItemBulkRestoreRequest",
    "ItemBulkTagRequest",
    "ItemCreate",
    "ItemFlagUpdate",
    "ItemLotCreate",
    "ItemLotRead",
    "ItemLotUpdate",
    "ItemRead",
    "ItemTemplateCreate",
    "ItemTemplateRead",
    "ItemTemplateUpdate",
    "ItemUpdate",
    "LoanCreate",
    "LoanRead",
    "LoanUpdate",
    "LocationCreate",
    "LocationKind",
    "LocationRead",
    "LocationUpdate",
    "LoginRequest",
    "MaintenanceCompletePayload",
    "MaintenanceCompletionRead",
    "MaintenanceTaskCreate",
    "MaintenanceTaskRead",
    "MaintenanceTaskUpdate",
    "ManualBundleCreate",
    "ManualBundleRead",
    "ManualBundleUpdate",
    "MeUpdate",
    "MembershipCreate",
    "MembershipDetail",
    "MembershipRead",
    "MembershipUpdate",
    "OIDCProviderInfo",
    "PhotoFromUrl",
    "PhotoRead",
    "PhotoUpdate",
    "RegisterRequest",
    "RestockRequest",
    "SessionInfo",
    "ShareLinkCreate",
    "ShareLinkRead",
    "SyncChange",
    "SyncChangeUpload",
    "SyncDocSummary",
    "SyncPullResponse",
    "SyncPushRequest",
    "SyncPushResponse",
    "SyncSnapshotResponse",
    "SyncSnapshotUpload",
    "TagCreate",
    "TagRead",
    "TagUpdate",
    "TemplateField",
    "TokenInfo",
    "UserCreate",
    "UserRead",
    "UserUpdate",
    "WebhookCreate",
    "WebhookDeliveryRead",
    "WebhookRead",
    "WebhookUpdate",
]
